/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/12-vinyl-record-dd27284e8c1a4622b3a0433c7cc8ee72
title: 12" Vinyl Record
*/
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei/useGLTF"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/vinyl.gltf")
  return (
    <group ref={group} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0]} rotation={[0.75, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                material={materials.REC0002_Textures}
                geometry={
                  nodes["#REC0002_33_Highway_To_Hell_#REC0002_Textures_0"]
                    .geometry
                }
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/vinyl.gltf")
